<?php

namespace ContainerAEfUITl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IvA9VMYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ivA9VMY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ivA9VMY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'team' => ['privates', '.errored..service_locator.ivA9VMY.App\\Entity\\Team', NULL, 'Cannot autowire service ".service_locator.ivA9VMY": it needs an instance of "App\\Entity\\Team" but this type has been excluded in "config/services.yaml".'],
            'teamRepository' => ['privates', 'App\\Repository\\TeamRepository', 'getTeamRepositoryService', true],
        ], [
            'team' => 'App\\Entity\\Team',
            'teamRepository' => 'App\\Repository\\TeamRepository',
        ]);
    }
}
