<?php

namespace ContainerAEfUITl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ivA9VMY.App\Entity\Team' shared service.
     *
     * @return \App\Entity\Team
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ivA9VMY": it needs an instance of "App\\Entity\\Team" but this type has been excluded in "config/services.yaml".');
    }
}
