<?php

namespace ContainerH3dXkxt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2Igu30aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2Igu30a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2Igu30a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'TeamPlayer' => ['privates', 'App\\Repository\\TeamPlayerRepository', 'getTeamPlayerRepositoryService', true],
            'mm' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'TeamPlayer' => 'App\\Repository\\TeamPlayerRepository',
            'mm' => '?',
        ]);
    }
}
