<?php

namespace ContainerH3dXkxt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UH1DCB3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uH1DCB3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uH1DCB3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'teamPlayerRepository' => ['privates', 'App\\Repository\\TeamPlayerRepository', 'getTeamPlayerRepositoryService', true],
        ], [
            'em' => '?',
            'teamPlayerRepository' => 'App\\Repository\\TeamPlayerRepository',
        ]);
    }
}
