<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH3dXkxt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH3dXkxt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH3dXkxt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH3dXkxt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH3dXkxt\App_KernelDevDebugContainer([
    'container.build_hash' => 'H3dXkxt',
    'container.build_id' => 'bffd6167',
    'container.build_time' => 1683795549,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH3dXkxt');
