<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_player_index' => [[], ['_controller' => 'App\\Controller\\PlayerController::index'], [], [['text', '/player/']], [], [], []],
    'app_player_buy' => [[], ['_controller' => 'App\\Controller\\PlayerController::buyPlayer'], [], [['text', '/player/buy']], [], [], []],
    'app_player_sell' => [[], ['_controller' => 'App\\Controller\\PlayerController::sellPlayer'], [], [['text', '/player/sell']], [], [], []],
    'app_team_index' => [[], ['_controller' => 'App\\Controller\\TeamController::index'], [], [['text', '/']], [], [], []],
    'app_team_new' => [[], ['_controller' => 'App\\Controller\\TeamController::new'], [], [['text', '/new']], [], [], []],
    'app_player_teamplayer' => [[], ['_controller' => 'App\\Controller\\TeamController::buyPlayer'], [], [['text', '/teamplayer']], [], [], []],
];
